# Path to reference fasta file
REFERENCE: "/mnt/data/ref/hg38.fa"

# Path to fastq files
READS: "reads/raw/"

# Path to the trimmed fastq files
TRIMMED: "reads/trimmed/"

# Path to the fastq files. Remember to create it with the setup file!
FASTQC: "reads/quality/"

# Path to alignment
ALIGNMENT: "alignment/"

# Path to alignment metrics
ALIGNMENT_QUAL: "alignment/quality"

# Path to all log files
LOGS: "logs/"

# Path to Picard 
PICARD: "/home/kzkedzierska/miniconda3/envs/atac/share/picard-2.19.0-0/picard.jar"
