# Path to reference fasta file
REFERENCE: "/mnt/data/ref/hg38.fa"

# Path to fastq files
READS: "reads/raw/"

# Path to the trimmed fastq files
TRIMMED: "reads/trimmed/"

# Path to the fastq files. Remember to create it with the setup file!
FASTQC: "reads/quality/"

# Path to alignment
ALIGNMENT: "algn/"

# Path to all log files
LOGS: "logs/"
